config/routes.rb
CafeGrader::Application.routes.draw do
  resources :tags
  get "sources/direct_edit"

  root :to => 'main#login'

  #logins
  get 'login/login',  to: 'login#login'

  resources :contests

  resources :sites

  resources :announcements do
    member do
      get 'toggle','toggle_front'
    end
  end

  resources :problems do
    member do
      get 'toggle'
      get 'toggle_test'
      get 'toggle_view_testcase'
      get 'stat'
    end
    collection do
      get 'turn_all_off'
      get 'turn_all_on'
      get 'import'
      get 'manage'
    end
  end

  resources :groups do
    member do
      post 'add_user', to: 'groups#add_user', as: 'add_user'
      delete 'remove_user/:user_id', to: 'groups#remove_user', as: 'remove_user'
      delete 'remove_all_user', to: 'groups#remove_all_user', as: 'remove_all_user'
      post 'add_problem', to: 'groups#add_problem', as: 'add_problem'
      delete 'remove_problem/:problem_id', to: 'groups#remove_problem', as: 'remove_problem'
      delete 'remove_all_problem', to: 'groups#remove_all_problem', as: 'remove_all_problem'
    end
    collection do

    end
  end

  resources :testcases, only: [] do
    member do 
      get 'download_input'
      get 'download_sol'
    end
    collection do
      get 'show_problem/:problem_id(/:test_num)' => 'testcases#show_problem', as: 'show_problem'
    end
  end

  resources :grader_configuration, controller: 'configurations'

  resources :users do
    member do
      get 'toggle_activate', 'toggle_enable', 'toggle_show_score'
      get 'stat'
    end
  end

  resources :submissions do
    member do
      get 'download'
      get 'compiler_msg'
      get 'rejudge'
    end
    collection do
      get 'prob/:problem_id', to: 'submissions#index', as: 'problem'
      get 'direct_edit_problem/:problem_id(/:user_id)', to: 'submissions#direct_edit_problem', as: 'direct_edit_problem'
      get 'get_latest_submission_status/:uid/:pid', to: 'submissions#get_latest_submission_status', as: 'get_latest_submission_status'
    end
  end



  #main
  get "main/list"
  get 'main/submission(/:id)', to: 'main#submission', as: 'main_submission'

  #user admin
  get 'user_admin/bulk_manage', to: 'user_admin#bulk_manage', as: 'bulk_manage_user_admin'
  post 'user_admin', to: 'user_admin#create'
  delete 'user_admin/:id', to: 'user_admin#destroy', as: 'user_admin_destroy'

  #report
  get 'report/current_score', to: 'report#current_score', as: 'report_current_score'
  get 'report/problem_hof(/:id)', to: 'report#problem_hof', as: 'report_problem_hof'
  get "report/login"
  get 'report/max_score', to: 'report#max_score', as: 'report_max_score'
  post 'report/show_max_score', to: 'report#show_max_score', as: 'report_show_max_score'


  #
  get 'tasks/view/:file.:ext' => 'tasks#view'
  get 'tasks/download/:id/:file.:ext' => 'tasks#download'
  get 'heartbeat/:id/edit' => 'heartbeat#edit'

  #grader
  get 'graders/list', to: 'graders#list', as: 'grader_list'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)', via:  [:get, :post]
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

  def self.published(contest_started=false)
    if contest_started
      where(published: true).where(frontpage: false).order(created_at: :desc)
    else
      where(published: true).where(frontpage: false).where(contest_only: false).order(created_at: :desc)
    end
  end

  def self.frontpage
    where(published: 1).where(frontpage: 1).order(created_at: :desc)
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController

  before_filter :admin_authorization

  in_place_edit_for :announcement, :published

  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.order(created_at: :desc)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        flash[:notice] = 'Announcement was successfully created.'
        format.html { redirect_to(@announcement) }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(announcement_params)
        flash[:notice] = 'Announcement was successfully updated.'
        format.html { redirect_to(@announcement) }
        format.js   {}
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.js   {}
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  def toggle
    @announcement = Announcement.find(params[:id])
    @announcement.update_attributes( published:  !@announcement.published? )
    respond_to do |format|
      format.js { render partial: 'toggle_button',
                  locals: {button_id: "#announcement_toggle_#{@announcement.id}",button_on: @announcement.published? } }
    end
  end

  def toggle_front
    @announcement = Announcement.find(params[:id])
    @announcement.update_attributes( frontpage:  !@announcement.frontpage? )
    respond_to do |format|
      format.js { render partial: 'toggle_button',
                  locals: {button_id: "#announcement_toggle_front_#{@announcement.id}",button_on: @announcement.frontpage? } }
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end

  private

    def announcement_params
      params.require(:announcement).permit(:author, :body, :published, :frontpage, :contest_only, :title)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/edit.html.haml
.container-fluid
  %h1 Editing announcement
  = error_messages_for :announcement
  .row
    .col-md-6
      = form_for(@announcement) do |f|
        .form-group
          %label Title
          = f.text_field :title, class: 'form-control'
        .form-group
          %label Notes
          (shown internally, used to organize announcements)
          = f.text_field :notes, class: 'form-control'
        .form-group
          %label Body
          = f.text_area  :body, class: 'form-control', style: 'height: 200px;'
        .form-group
          %label Author
          = f.text_field :author, class: 'form-control'
        .checkbox
          %label 
            = f.check_box :published
            Published
        .checkbox
          %label 
            = f.check_box :frontpage
            Show on front page?
        .checkbox
          %label 
            = f.check_box :contest_only
            Show only in contest?
        = f.submit "Update", class: 'btn btn-primary'
        = link_to 'Show', @announcement, class: 'btn btn-default'
        = link_to 'Back', announcements_path, class: 'btn btn-default'

app/views/announcements/index.html.haml
%h1 Listing announcements

= link_to '+ Add announcement', new_announcement_path, class: 'btn btn-success'
%br
%br

%table.table.table-striped
  %thead
    %th Updated
    %th Announcement
    %th Author
    %th{style: 'width: 100px'} Published?
    %th{style: 'width: 100px'}Front?
    %th
    %th
  - for announcement in @announcements
    %tr
      - @announcement = announcement
      %td= time_ago_in_words announcement.updated_at
      %td
        - if !announcement.title.blank?
          %b Title:
          = h announcement.title
          %br/
        - if !announcement.notes.blank?
          %b
            Notes: #{h announcement.notes}
          %br/
        = h announcement.body
      %td= h announcement.author
      %td= toggle_button(announcement.published?, toggle_announcement_path(@announcement), "announcement_toggle_#{@announcement.id}", {size: 'btn-sm'})
      %td= toggle_button(announcement.frontpage?, toggle_front_announcement_path(@announcement), "announcement_toggle_front_#{@announcement.id}", {size: 'btn-sm'})
      %td= link_to 'Edit', edit_announcement_path(announcement), class: 'btn btn-block btn-sm btn-info'
      %td= link_to 'Destroy', announcement, :confirm => 'Are you sure?', :method => :delete, class: "btn btn-block btn-sm btn-danger"
%br

= link_to '+ Add announcement', new_announcement_path, class: 'btn btn-success'

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= error_messages_for :announcement %>

<%= form_for(@announcement) do |f| %>
  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <b>Notes</b> (shown internally, used to organize announcements)<br />
    <%= f.text_field :notes %>
  </p>

  <p>
    <b>Body</b><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <b>Author</b><br />
    <%= f.text_field :author %>
  </p>

  <p>
    <b>Published</b><br />
    <%= f.check_box :published %>
  </p>

  <p>
    <b>Show on front page?</b><br />
    <%= f.check_box :frontpage %>
  </p>

  <p>
    <b>Show only in contest?</b><br />
    <%= f.check_box :contest_only %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p>
  <b>Author:</b>
  <%=h @announcement.author %>
</p>

<p>
  <b>Title:</b>
  <%=h @announcement.title %>
</p>

<p>
  <b>Notes:</b>
  <%=h @announcement.notes %>
</p>

<p>
  <b>Body:</b>
  <%=h markdown(@announcement.body) %>
</p>

<p>
  <b>Published:</b>
  <%=h @announcement.published %>
</p>

<p>
  <b>Show on front page:</b>
  <%=h @announcement.frontpage %>
</p>

<p>
  <b>Show only in contest:</b>
  <%=h @announcement.contest_only %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>