config/routes.rb
CafeGrader::Application.routes.draw do
  resources :tags
  get "sources/direct_edit"

  root :to => 'main#login'

  #logins
  get 'login/login',  to: 'login#login'

  resources :contests

  resources :sites

  resources :announcements do
    member do
      get 'toggle','toggle_front'
    end
  end

  resources :problems do
    member do
      get 'toggle'
      get 'toggle_test'
      get 'toggle_view_testcase'
      get 'stat'
    end
    collection do
      get 'turn_all_off'
      get 'turn_all_on'
      get 'import'
      get 'manage'
    end
  end

  resources :groups do
    member do
      post 'add_user', to: 'groups#add_user', as: 'add_user'
      delete 'remove_user/:user_id', to: 'groups#remove_user', as: 'remove_user'
      delete 'remove_all_user', to: 'groups#remove_all_user', as: 'remove_all_user'
      post 'add_problem', to: 'groups#add_problem', as: 'add_problem'
      delete 'remove_problem/:problem_id', to: 'groups#remove_problem', as: 'remove_problem'
      delete 'remove_all_problem', to: 'groups#remove_all_problem', as: 'remove_all_problem'
    end
    collection do

    end
  end

  resources :testcases, only: [] do
    member do 
      get 'download_input'
      get 'download_sol'
    end
    collection do
      get 'show_problem/:problem_id(/:test_num)' => 'testcases#show_problem', as: 'show_problem'
    end
  end

  resources :grader_configuration, controller: 'configurations'

  resources :users do
    member do
      get 'toggle_activate', 'toggle_enable', 'toggle_show_score'
      get 'stat'
    end
  end

  resources :submissions do
    member do
      get 'download'
      get 'compiler_msg'
      get 'rejudge'
    end
    collection do
      get 'prob/:problem_id', to: 'submissions#index', as: 'problem'
      get 'direct_edit_problem/:problem_id(/:user_id)', to: 'submissions#direct_edit_problem', as: 'direct_edit_problem'
      get 'get_latest_submission_status/:uid/:pid', to: 'submissions#get_latest_submission_status', as: 'get_latest_submission_status'
    end
  end



  #main
  get "main/list"
  get 'main/submission(/:id)', to: 'main#submission', as: 'main_submission'

  #user admin
  get 'user_admin/bulk_manage', to: 'user_admin#bulk_manage', as: 'bulk_manage_user_admin'
  post 'user_admin', to: 'user_admin#create'
  delete 'user_admin/:id', to: 'user_admin#destroy', as: 'user_admin_destroy'

  #report
  get 'report/current_score', to: 'report#current_score', as: 'report_current_score'
  get 'report/problem_hof(/:id)', to: 'report#problem_hof', as: 'report_problem_hof'
  get "report/login"
  get 'report/max_score', to: 'report#max_score', as: 'report_max_score'
  post 'report/show_max_score', to: 'report#show_max_score', as: 'report_show_max_score'


  #
  get 'tasks/view/:file.:ext' => 'tasks#view'
  get 'tasks/download/:id/:file.:ext' => 'tasks#download'
  get 'heartbeat/:id/edit' => 'heartbeat#edit'

  #grader
  get 'graders/list', to: 'graders#list', as: 'grader_list'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)', via:  [:get, :post]
end

app/controllers/user_admin_controller.rb
require 'csv'

class UserAdminController < ApplicationController

  include MailHelperMethods

  before_filter :admin_authorization

  # GETs should be safe (see http://www.w3.org/2001/tag/doc/whenToUseGet.html)
  verify :method => :post, :only => [
                                      :create, :create_from_list, 
                                      :update, 
                                      :manage_contest, 
                                      :bulk_mail 
                                    ],
         :redirect_to => { :action => :list }

  def index
    @user_count = User.count
    if params[:page] == 'all'
      @users = User.all
      @paginated = false
    else
      @users = User.paginate :page => params[:page]
      @paginated = true
    end
    @users = User.all
    @hidden_columns = ['hashed_password', 'salt', 'created_at', 'updated_at']
    @contests = Contest.enabled
  end

  def active
    sessions = ActiveRecord::SessionStore::Session.where("updated_at >= ?", 60.minutes.ago)
    @users = []
    sessions.each do |session|
      if session.data[:user_id]
        @users << User.find(session.data[:user_id])
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.activated = true
    if @user.save
      flash[:notice] = 'User was successfully created.'
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end    
  end

  def clear_last_ip
    @user = User.find(params[:id])
    @user.last_ip = nil
    @user.save
    redirect_to action: 'index', page: params[:page]
  end

  def create_from_list
    lines = params[:user_list]

    note = []

    lines.split("\n").each do |line|
      items = line.chomp.split(',')
      if items.length>=2
        login = items[0]
        full_name = items[1]
        remark =''
        user_alias = ''

        added_random_password = false
        if items.length >= 3 and items[2].chomp(" ").length > 0;
          password = items[2].chomp(" ")
        else
          password = random_password
          add_random_password=true;
        end

        if items.length>= 4 and items[3].chomp(" ").length > 0;
          user_alias = items[3].chomp(" ")
        else
          user_alias = login
        end

        if items.length>=5
          remark = items[4].strip;
        end

        user = User.find_by_login(login)
        if (user)
          user.full_name = full_name
          user.password = password
          user.remark = remark
        else
          user = User.new({:login => login,
                            :full_name => full_name,
                            :password => password,
                            :password_confirmation => password,
                            :alias => user_alias,
                            :remark => remark})
        end
        user.activated = true
        user.save

        if added_random_password
          note << "'#{login}' (+)"
        else
          note << login
        end
      end
    end
    flash[:success] = 'User(s) ' + note.join(', ') + 
      ' were successfully created.  ' +
      '( (+) - created with random passwords.)'   
    redirect_to :action => 'index'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = 'User was successfully updated.'
      redirect_to :action => 'show', :id => @user
    else
      render :action => 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  def user_stat
    if params[:commit] == 'download csv'
      @problems = Problem.all
    else
      @problems = Problem.available_problems
    end
    @users = User.includes(:contests, :contest_stat).where(enabled: true) 
    @scorearray = Array.new
    @users.each do |u|
      ustat = Array.new
      ustat[0] = u
      @problems.each do |p|
        sub = Submission.find_last_by_user_and_problem(u.id,p.id)
        if (sub!=nil) and (sub.points!=nil) and p and p.full_score
          ustat << [(sub.points.to_f*100/p.full_score).round, (sub.points>=p.full_score)]
        else
          ustat << [0,false]
        end
      end
      @scorearray << ustat
    end
    if params[:commit] == 'download csv' then
      csv = gen_csv_from_scorearray(@scorearray,@problems)
      send_data csv, filename: 'last_score.csv'
    else
      render template: 'user_admin/user_stat'
    end
  end

  def user_stat_max
    if params[:commit] == 'download csv'
      @problems = Problem.all
    else
      @problems = Problem.available_problems
    end
    @users = User.includes(:contests).includes(:contest_stat).all
    @scorearray = Array.new
    #set up range from param
    since_id = params.fetch(:since_id, 0).to_i
    until_id = params.fetch(:until_id, 0).to_i
    @users.each do |u|
      ustat = Array.new
      ustat[0] = u
      @problems.each do |p|
        max_points = 0
        Submission.find_in_range_by_user_and_problem(u.id,p.id,since_id,until_id).each do |sub|
          max_points = sub.points if sub and sub.points and (sub.points > max_points)
        end
        ustat << [(max_points.to_f*100/p.full_score).round, (max_points>=p.full_score)]
      end
      @scorearray << ustat
    end

    if params[:commit] == 'download csv' then
      csv = gen_csv_from_scorearray(@scorearray,@problems)
      send_data csv, filename: 'max_score.csv'
    else
      render template: 'user_admin/user_stat'
    end
  end

  def import
    if params[:file]==''
      flash[:notice] = 'Error importing no file'
      redirect_to :action => 'index' and return
    end
    import_from_file(params[:file])
  end

  def random_all_passwords
    users = User.all
    @prefix = params[:prefix] || ''
    @non_admin_users = User.find_non_admin_with_prefix(@prefix)
    @changed = false
    if request.request_method == 'POST'
      @non_admin_users.each do |user|
        password = random_password
        user.password = password
        user.password_confirmation = password
        user.save
      end
      @changed = true
    end
  end


  # contest management

  def contests
    @contest, @users = find_contest_and_user_from_contest_id(params[:id])
    @contests = Contest.enabled
  end

  def assign_from_list
    contest_id = params[:users_contest_id]
    org_contest, users = find_contest_and_user_from_contest_id(contest_id)
    contest = Contest.find(params[:new_contest][:id])
    if !contest
      flash[:notice] = 'Error: no contest'
      redirect_to :action => 'contests', :id =>contest_id
    end

    note = []
    users.each do |u|
      u.contests = [contest]
      note << u.login
    end
    flash[:notice] = 'User(s) ' + note.join(', ') + 
      " were successfully reassigned to #{contest.title}." 
    redirect_to :action => 'contests', :id =>contest.id
  end

  def add_to_contest
    user = User.find(params[:id])
    contest = Contest.find(params[:contest_id])
    if user and contest
      user.contests << contest
    end
    redirect_to :action => 'index'
  end

  def remove_from_contest
    user = User.find(params[:id])
    contest = Contest.find(params[:contest_id])
    if user and contest
      user.contests.delete(contest)
    end
    redirect_to :action => 'index'
  end

  def contest_management
  end

  def manage_contest
    contest = Contest.find(params[:contest][:id])
    if !contest
      flash[:notice] = 'You did not choose the contest.'
      redirect_to :action => 'contest_management' and return
    end

    operation = params[:operation]

    if not ['add','remove','assign'].include? operation
      flash[:notice] = 'You did not choose the operation to perform.'
      redirect_to :action => 'contest_management' and return
    end

    lines = params[:login_list]
    if !lines or lines.blank?
      flash[:notice] = 'You entered an empty list.'
      redirect_to :action => 'contest_management' and return
    end

    note = []
    users = []
    lines.split("\n").each do |line|
      user = User.find_by_login(line.chomp)
      if user
        if operation=='add'
          if ! user.contests.include? contest
            user.contests << contest
          end
        elsif operation=='remove'
          user.contests.delete(contest)
        else
          user.contests = [contest]
        end

        if params[:reset_timer]
          user.contest_stat.forced_logout = true
          user.contest_stat.reset_timer_and_save
        end

        if params[:notification_emails]
          send_contest_update_notification_email(user, contest) 
        end

        note << user.login
        users << user
      end
    end

    if params[:reset_timer]
      logout_users(users)
    end

    flash[:notice] = 'User(s) ' + note.join(', ') + 
      ' were successfully modified.  ' 
    redirect_to :action => 'contest_management'    
  end

  # admin management

  def admin
    @admins = User.all.find_all {|user| user.admin? }
  end

  def grant_admin
    login = params[:login]
    user = User.find_by_login(login)
    if user!=nil
      admin_role = Role.find_by_name('admin')
      user.roles << admin_role
    else
      flash[:notice] = 'Unknown user'
    end
    flash[:notice] = 'User added as admins'
    redirect_to :action => 'admin'
  end

  def revoke_admin
    user = User.find(params[:id])
    if user==nil
      flash[:notice] = 'Unknown user'
      redirect_to :action => 'admin' and return
    elsif user.login == 'root'
      flash[:notice] = 'You cannot revoke admisnistrator permission from root.'
      redirect_to :action => 'admin' and return
    end

    admin_role = Role.find_by_name('admin')
    user.roles.delete(admin_role)
    flash[:notice] = 'User permission revoked'
    redirect_to :action => 'admin'
  end

  # mass mailing

  def mass_mailing
  end

  def bulk_mail
    lines = params[:login_list]
    if !lines or lines.blank?

app/helpers/user_admin_helper.rb
module UserAdminHelper
end

app/views/user_admin/_form.html.haml
= error_messages_for 'user'
/ [form:user]
.form-group
  %label.col-md-2.control-label{for: :login} Login
  .col-md-4
    = text_field 'user', 'login', class: 'form-control'
  .col-md-6
.form-group
  %label.col-md-2.control-label{for: :full_name} Full name
  .col-md-4
    = text_field 'user', 'full_name', class: 'form-control'
  .col-md-6
.form-group
  %label.col-md-2.control-label{for: :password} Password
  .col-md-4
    = password_field 'user', 'password', class: 'form-control'
  .col-md-6
.form-group
  %label.col-md-2.control-label{for: :password_confirmation} Password (confirm)
  .col-md-4
    = password_field 'user', 'password_confirmation', class: 'form-control'
  .col-md-6
.form-group
  %label.col-md-2.control-label{for: :email} E-mail
  .col-md-4
    = email_field 'user', 'email', class: 'form-control'
  .col-md-6
.form-group
  %label.col-md-2.control-label{for: :alias} Alias
  .col-md-4
    = text_field 'user', 'alias', class: 'form-control'
  .col-md-6
.form-group
  %label.col-md-2.control-label{for: :remark} Remark
  .col-md-4
    = text_field 'user', 'remark', class: 'form-control'
  .col-md-6
/ [eoform:user]

app/views/user_admin/_submission_range.html.haml
= form_tag({action: :user_stat_max })  do
  .submitbox
    %table
      %tr
        %td{colspan: 6, style: 'font-weight: bold'} Query maximum score in submission range
      %tr
        %td{style: 'width: 120px; font-weight: bold'} Submission ID:
        %td{align: 'right'} From:
        %td= text_field_tag 'since_id', params[:since_id], style: 'width:40px'
        %td To:
        %td= text_field_tag 'until_id', params[:until_id], style: 'width:40px'
        %td= submit_tag 'query'
      %tr
        %td 
        %td{colspan: 5} Leave blank for uncondition

app/views/user_admin/active.html.haml
%h1 Active users

%i
  I.e., those users that interacts with the system with in the last 60 minutes.
%br/

= link_to '[go back to index]', :action => 'index'

%table
  %tr
    %th #
    %th login
    %th full name
  - counter = 0
  - for user in @users
    %tr
      %td= counter += 1
      %td= user.login
      %td= user.full_name

app/views/user_admin/admin.html.haml
%h1 Administrators

%table{:class => 'info'}
  %tr{:class => 'info-head'}
    %th #
    %th Login
    %th Full name
    %th 
  - @admins.each_with_index do |user, i|
    %tr
      %td= i+1
      %td= user.login
      %td= user.full_name
      %td
        - if user.login!='root'
          = link_to '[revoke]', :action => 'revoke_admin', :id => user.id
%hr

= form_tag :action => 'grant_admin' do
  Grant admin permission to:
  = text_field_tag 'login'
  = submit_tag 'Grant'

%hr/
= link_to '[go back to index]', :action => 'index'

app/views/user_admin/bulk_manage.html.haml
%h1 Bulk Manage User

= form_tag bulk_manage_user_admin_path
.row
  .col-md-6
    .panel.panel-primary
      .panel-title.panel-heading
        Filter User
      .panel-body
        Filtering users whose login match the following MySQL regex
        .form-group
          = label_tag "regex", 'Regex Pattern'
          = text_field_tag "regex", params[:regex], class: 'form-control'
        %p
          Example
        %ul
          %li
            %code root
            matches every user whose login contains "root"
          %li
            %code ^56
            matches every user whose login starts with "56"
          %li
            %code 21$
            matches every user whose login ends with "21"
  .col-md-6
    .panel.panel-primary
      .panel-title.panel-heading
        Action
      .panel-body
        .row.form-group
          .col-md-6
            %label.checkbox-inline
              = check_box_tag "enabled", true, params[:enabled]
              Change "Enabled" to
          .col-md-3
            %label.radio-inline
              = radio_button_tag "enable", 1, params[:enable] == '1', id: 'enable-yes'
              Yes
          .col-md-3
            %label.radio-inline
              = radio_button_tag "enable", 0, params[:enable] == '0', id: 'enable-no'
              No
        .row.form-group
          .col-md-6
            %label.checkbox-inline
              = check_box_tag "gen_password", true, params[:gen_password]
              Generate new random password
        .row.form-group
          .col-md-4
            %label.checkbox-inline
              = check_box_tag "add_group", true, params[:add_group]
              Add users to group
          %label.col-md-3.control-label.text-right Group name
          .col-md-5
            = select_tag "group_name", options_from_collection_for_select( Group.all, 'id','name',params[:group_name]), id: 'group_name',class: 'form-control select2'


.row
  .col-md-12
    = submit_tag "Preview Result", class: 'btn btn-default'
- if @users
  .row
    .col-md-4
      - if @action
        %h2 Confirmation
        - if @action[:set_enable]
          .alert.alert-info The following users will be set #{(@action[:enabled] ? 'enable' : 'disable')}.
        - if @action[:gen_password]
          .alert.alert-info The password of the following users will be randomly generated.
  .row
    .col-md-4
      = submit_tag "Perform", class: 'btn btn-primary'
  .row
    .col-md-12
      The pattern matches #{@users.count} following users.
      %br
      - @users.each do |user|
        = user.login
        = ' '
        = user.full_name
        = ' '
        = "(#{user.remark})" if user.remark
        %br

app/views/user_admin/contest_management.html.haml
%h1 Bulk edit users in contests

= form_tag :action => 'manage_contest' do
  List users' login below; one per line.
  %br/
  = text_area_tag 'login_list', nil, :rows => 23, :cols => 80
  %br/
  %table
    %tr
      %td{:valign => 'top'}
        You want to
        = select(nil,"operation",[['assign users to','assign'],['add users to','add'],['remove users from','remove']])
        contest
        = select("contest","id",Contest.all.collect {|c| [c.title, c.id]})
        and also
      %td
        = check_box_tag 'reset_timer'
        Auto-reset current contest timer.
        %br/
        = check_box_tag 'notification_emails'
        Send notification email(s).

  = submit_tag "Perform action!", :confirm => 'Are you sure?'

%hr/
= link_to '[go back to index]', :action => 'index'

app/views/user_admin/edit.html.haml
%h1 Editing user

= form_tag( {:action => 'update', :id => @user}, {class: 'form-horizontal'}) do
  = error_messages_for 'user'
  = render partial: "form"
  .form-group
    .col-md-offset-2.col-md-4
      = submit_tag "Edit", class: 'btn btn-primary'


= link_to 'Show', :action => 'show', :id => @user 
|
= link_to 'Back', :action => ''

app/views/user_admin/index.html.haml
%h1 Users

.panel.panel-primary
  .panel-title.panel-heading
    Quick Add
  .panel-body
    = form_tag( {method: 'post'}, {class: 'form-inline'})  do
      .form-group
        = label_tag 'user_login', 'Login'
        = text_field 'user', 'login', :size => 10,class: 'form-control'
      .form-group
        = label_tag 'user_full_name', 'Full Name'
        = text_field 'user', 'full_name', :size => 10,class: 'form-control'
      .form-group
        = label_tag 'user_password', 'Password'
        = text_field 'user', 'password', :size => 10,class: 'form-control'
      .form-group
        = label_tag 'user_password_confirmation', 'Confirm'
        = text_field 'user', 'password_confirmation', :size => 10,class: 'form-control'
      .form-group
        = label_tag 'user_email', 'email'
        = text_field 'user', 'email', :size => 10,class: 'form-control'
      =submit_tag "Create", class: 'btn btn-primary'

.panel.panel-primary
  .panel-title.panel-heading
    Import from site management
  .panel-body
    = form_tag({:action => 'import'}, :multipart => true,class: 'form form-inline') do
      .form-group
        = label_tag :file, 'File:'
        .input-group
          %span.input-group-btn
            %span.btn.btn-default.btn-file
              Browse
              = file_field_tag 'file'
          = text_field_tag '' , nil, {readonly: true, class: 'form-control'}
      = submit_tag 'Submit', class: 'btn btn-default'


%p
  = link_to '+ New user', { :action => 'new' }, { class: 'btn btn-success '}
  = link_to '+ New list of users', { :action => 'new_list' }, { class: 'btn btn-success '}
  = link_to 'Bulk Manage', bulk_manage_user_admin_path , { class: 'btn btn-default btn-info'}
  = link_to 'View administrators',{ :action => 'admin'}, { class: 'btn btn-default '}
  = link_to 'Random passwords',{ :action => 'random_all_passwords'}, { class: 'btn btn-default '}
  = link_to 'View active users',{ :action => 'active'}, { class: 'btn btn-default '}
  = link_to 'Mass mailing',{ :action => 'mass_mailing'}, { class: 'btn btn-default '}

- if GraderConfiguration.multicontests?
  %br/
  %b Multi-contest:
  = link_to '[Manage bulk users in contests]', :action => 'contest_management'
  View users in:
  - @contests.each do |contest|
    = link_to "[#{contest.name}]", :action => 'contests', :id => contest.id
  = link_to "[no contest]", :action => 'contests', :id => 'none'

-# Total #{@user_count} users |
-# - if !@paginated
-#   Display all users.
-#   \#{link_to '[show in pages]', :action => 'index', :page => '1'}
-# - else
-#   Display in pages.
-#   \#{link_to '[display all]', :action => 'index', :page => 'all'} |
-#   \#{will_paginate @users, :container => false}


%table.table.table-hover.table-condense.datatable
  %thead
    %th Login
    %th Full name
    %th email
    %th Remark
    %th 
      Activated
      %sup{class: 'text-primary',data: {toggle: 'tooltip', placement: 'top'}, title: 'User has already confirmed the email?' } [?]
    %th 
      Enabled
      %sup{class: 'text-primary',data: {toggle: 'tooltip', placement: 'top'}, title: 'Allow the user to login?' } [?]
    %th
      Show Score in Scoreboard
      %sup{class: 'text-primary',data: {toggle: 'tooltip', placement: 'top'}, title: 'Show result in scoreboard?' } [?]
    %th Last IP
    %th
    %th
    %th
    %th
  - for user in @users
    %tr
      %td= link_to user.login, stat_user_path(user)
      %td= user.full_name
      %td= user.email
      %td= user.remark
      %td= toggle_button(user.activated?, toggle_activate_user_path(user),"toggle_activate_user_#{user.id}")
      %td= toggle_button(user.enabled?, toggle_enable_user_path(user),"toggle_enable_user_#{user.id}")
      %td= toggle_button(user.show_score?, toggle_show_score_user_path(user),"toggle_show_score_user_#{user.id}")
      %td= user.last_ip
      %td= link_to 'Clear IP', {:action => 'clear_last_ip', :id => user, :page=>params[:page]}, :confirm => 'This will reset last logging in ip of the user, are you sure?', class: 'btn btn-default btn-xs btn-block'
      %td= link_to 'Show', {:action => 'show', :id => user}, class: 'btn btn-default btn-xs btn-block'
      %td= link_to 'Edit', {:action => 'edit', :id => user}, class: 'btn btn-default btn-xs btn-block'
      %td= link_to 'Destroy', user_admin_destroy_path(user), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger btn-xs btn-block'
%br/
= link_to '+ New user', { :action => 'new' }, { class: 'btn btn-success '}
= link_to '+ New list of users', { :action => 'new_list' }, { class: 'btn btn-success '}

:javascript
  $('.datatable').DataTable({
    'pageLength': 50
  });

app/views/user_admin/mass_mailing.html.haml
%h1 Send mass e-mails

= form_tag :action => 'bulk_mail' do
  %b List recipients' login below; one per line.
  %br/
  = text_area_tag 'login_list', nil, :rows => 7, :cols => 80
  %br/
  %b Subject:
  = text_field_tag 'subject', '', :size => 60
  %br/
  %b Email body:
  %br/
  = text_area_tag 'email_body', nil, :rows => 11, :cols => 80
  %br/

  = submit_tag "Send mails", :confirm => 'Are you sure?'

%hr/
= link_to '[go back to index]', :action => 'index'

app/views/user_admin/new.html.haml
%h1 New user
= form_tag( {action: 'create'}, { class: 'form-horizontal'}) do
  = render :partial => 'form'
  .form-group
    .col-md-offset-2.col-md-10
      = submit_tag "Create", class: 'btn btn-primary'
= link_to 'Back', :action => 'index'

app/views/user_admin/new_list.html.erb
<h1>Adding list of users</h1>

<%= form_tag :action => 'create_from_list' do %>
  <%= submit_tag 'create users',class: 'btn btn-success'%><br/>
List of user information in this format: <tt>user_id,name(,passwd(,alias(,remark)))</tt><br/>
Note that <tt>passwd, alias</tt> and <tt> remark </tt>is optional.<br />
When <tt>passwd</tt> or <tt>alias</tt> is empty, the original value will be used instead.<br/>
<%= text_area_tag 'user_list', nil, :rows => 50, :cols => 80 %>
<% end %>

app/views/user_admin/random_all_passwords.html.haml
%h1 Random user passwords

- if @changed
  %p 
    %b Done!
    Here's a new password list. 
    Go back to
    = (link_to '[user list]', :action => 'index') + '.'
  %br/
  %table
    %tr
      %th Login
      %th Fullname
      %th Password
    - for u in @non_admin_users
      %tr
        %td= u.login
        %td= u.full_name
        %td
          %tt= u.password

- else
  - if @prefix!=''
    Current prefix:
    = @prefix
  = form_tag((url_for :action => 'random_all_passwords'), :method => 'get') do
    Change prefix
    = text_field_tag 'prefix'
    = submit_tag 'Change'

  This will change passwords of the following users.
  %ul
    - for u in @non_admin_users
      %li= u.login

  = form_tag((url_for :action => 'random_all_passwords'), :method => 'post') do
    = hidden_field_tag 'prefix', @prefix
    Are you sure?
    = submit_tag 'Go ahead'

app/views/user_admin/show.html.haml
%h1 User information
- for column in User.content_columns
  %p
    %b
      = column.human_name
      \:
    = h @user.send(column.name)
%p
  %strong Group
  \:
  = @user.groups.map{ |x| link_to(x.name,group_path(x)).html_safe}.join(', ').html_safe
= link_to 'Edit', :action => 'edit', :id => @user
|
= link_to 'Back', :action => 'index'

app/views/user_admin/user_stat.html.haml
/- content_for :header do
/ = javascript_include_tag 'local_jquery'
/ = stylesheet_link_tag 'tablesorter-theme.cafe'

%script{:type=>"text/javascript"}
  $(function () {
  $('#since_datetime').datetimepicker({ showButtonPanel: true, dateFormat: "yy-mm-dd", controlType: "slider"} );
  $('#until_datetime').datetimepicker({ showButtonPanel: true, dateFormat: "yy-mm-dd", controlType: "slider"} );
  /$('#my_table').tablesorter({widgets: ['zebra']});
  });

%h1 User grading results
%h2= params[:action] == 'user_stat' ? "Show scores from latest submission" : "Show max scores in submission range"


- if @problem and @problem.errors
  =error_messages_for 'problem'

= render partial: 'submission_range'

- if params[:action] == 'user_stat'
  %h3 Latest score
  = link_to '[download csv with all problems]', controller: :user_admin, action: :user_stat, commit: 'download csv'
- else
  %h3 Max score
  = link_to '[Show only latest submissions]', controller: :user_admin, action: :user_stat
  = link_to '[download csv with all problems]', controller: :user_admin, action: :user_stat_max, commit: 'download csv'

%table.table.sortable.table-striped.table-bordered
  %thead
    %tr
      %th Login
      %th Name
      %th Activated?
      %th Logged_in
      %th Contest(s)
      %th Remark
      - @problems.each do |p|
        %th.text-right= p.name
      %th.text-right Total
      %th.text-right Passed
  %tbody
    - @scorearray.each do |sc|
      %tr
        - total,num_passed = 0,0
        - sc.each_index do |i|
          - if i == 0
            %td= link_to sc[i].login, controller: 'users', action: 'profile', id: sc[i]
            %td= sc[i].full_name
            %td= sc[i].activated
            %td= sc[i].try(:contest_stat).try(:started_at) ? 'yes' : 'no'
            %td= sc[i].contests.collect {|c| c.name}.join(', ') 
            %td= sc[i].remark
          - else
            %td.text-right= sc[i][0]
            - total += sc[i][0]
            - num_passed += 1 if sc[i][1]
        %td.text-right= total 
        %td.text-right= num_passed
:javascript
  $.bootstrapSortable(true,'reversed')