config/routes.rb
CafeGrader::Application.routes.draw do
  resources :tags
  get "sources/direct_edit"

  root :to => 'main#login'

  #logins
  get 'login/login',  to: 'login#login'

  resources :contests

  resources :sites

  resources :announcements do
    member do
      get 'toggle','toggle_front'
    end
  end

  resources :problems do
    member do
      get 'toggle'
      get 'toggle_test'
      get 'toggle_view_testcase'
      get 'stat'
    end
    collection do
      get 'turn_all_off'
      get 'turn_all_on'
      get 'import'
      get 'manage'
    end
  end

  resources :groups do
    member do
      post 'add_user', to: 'groups#add_user', as: 'add_user'
      delete 'remove_user/:user_id', to: 'groups#remove_user', as: 'remove_user'
      delete 'remove_all_user', to: 'groups#remove_all_user', as: 'remove_all_user'
      post 'add_problem', to: 'groups#add_problem', as: 'add_problem'
      delete 'remove_problem/:problem_id', to: 'groups#remove_problem', as: 'remove_problem'
      delete 'remove_all_problem', to: 'groups#remove_all_problem', as: 'remove_all_problem'
    end
    collection do

    end
  end

  resources :testcases, only: [] do
    member do 
      get 'download_input'
      get 'download_sol'
    end
    collection do
      get 'show_problem/:problem_id(/:test_num)' => 'testcases#show_problem', as: 'show_problem'
    end
  end

  resources :grader_configuration, controller: 'configurations'

  resources :users do
    member do
      get 'toggle_activate', 'toggle_enable', 'toggle_show_score'
      get 'stat'
    end
  end

  resources :submissions do
    member do
      get 'download'
      get 'compiler_msg'
      get 'rejudge'
    end
    collection do
      get 'prob/:problem_id', to: 'submissions#index', as: 'problem'
      get 'direct_edit_problem/:problem_id(/:user_id)', to: 'submissions#direct_edit_problem', as: 'direct_edit_problem'
      get 'get_latest_submission_status/:uid/:pid', to: 'submissions#get_latest_submission_status', as: 'get_latest_submission_status'
    end
  end



  #main
  get "main/list"
  get 'main/submission(/:id)', to: 'main#submission', as: 'main_submission'

  #user admin
  get 'user_admin/bulk_manage', to: 'user_admin#bulk_manage', as: 'bulk_manage_user_admin'
  post 'user_admin', to: 'user_admin#create'
  delete 'user_admin/:id', to: 'user_admin#destroy', as: 'user_admin_destroy'

  #report
  get 'report/current_score', to: 'report#current_score', as: 'report_current_score'
  get 'report/problem_hof(/:id)', to: 'report#problem_hof', as: 'report_problem_hof'
  get "report/login"
  get 'report/max_score', to: 'report#max_score', as: 'report_max_score'
  post 'report/show_max_score', to: 'report#show_max_score', as: 'report_show_max_score'


  #
  get 'tasks/view/:file.:ext' => 'tasks#view'
  get 'tasks/download/:id/:file.:ext' => 'tasks#download'
  get 'heartbeat/:id/edit' => 'heartbeat#edit'

  #grader
  get 'graders/list', to: 'graders#list', as: 'grader_list'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)', via:  [:get, :post]
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :groups_problems, class_name: GroupProblem
  has_many :problems, :through => :groups_problems

  has_many :groups_users, class_name: GroupUser
  has_many :users, :through => :groups_users

  #has_and_belongs_to_many :problems
  #has_and_belongs_to_many :users


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy,
                                   :add_user, :remove_user,:remove_all_user,
                                   :add_problem, :remove_problem,:remove_all_problem,
                                  ]
  before_action :authenticate, :admin_authorization

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  def remove_user
    user = User.find(params[:user_id])
    @group.users.delete(user)
    redirect_to group_path(@group), flash: {success: "User #{user.login} was removed from the group #{@group.name}"}
  end

  def remove_all_user
    @group.users.clear
    redirect_to group_path(@group), alert: 'All users removed'
  end

  def remove_all_problem
    @group.problems.clear
    redirect_to group_path(@group), alert: 'All problems removed'
  end

  def add_user
    user = User.find(params[:user_id])
    begin
      @group.users << user
      redirect_to group_path(@group), flash: { success: "User #{user.login} was add to the group #{@group.name}"}
    rescue => e
      redirect_to group_path(@group), alert: e.message
    end
  end

  def remove_problem
    problem = Problem.find(params[:problem_id])
    @group.problems.delete(problem)
    redirect_to group_path(@group), flash: {success: "Problem #{problem.name} was removed from the group #{@group.name}" }
  end

  def add_problem
    problem = Problem.find(params[:problem_id])
    begin
      @group.problems << problem
      redirect_to group_path(@group), flash: {success: "Problem #{problem.name} was add to the group #{@group.name}" }
    rescue => e
      redirect_to group_path(@group), alert: e.message
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .form-group.field
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group.field
    = f.label :description
    = f.text_field :description, class: 'form-control'
  .form-group.actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Groups

%p
  = link_to 'New Group', new_group_path, class: 'btn btn-primary'
%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.name
        %td= group.description
        %td= link_to 'View', group, class: 'btn btn-default'
        %td= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

%br

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p
  %b Name:
  = @group.name
%p
  %b Description:
  = @group.description

%br
= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

.row
  .col-md-12
    %h1 Group details
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        .panel-title Users in this group
      .panel-body
        =form_tag add_user_group_path(@group), class: 'form-inline' do
          .form-group
            =label_tag :user_id, "User"
            =select_tag :user_id, options_from_collection_for_select(User.all,'id','full_name'), class: 'select2'
          =submit_tag "Add",class: 'btn btn-primary'


        %table.table.table-hover
          %thead
            %tr
              %th Login
              %th Full name
              %th Remark
              %th= link_to 'Remove All', remove_all_user_group_path(@group), method: :delete, :data => { :confirm => "Remove ALL USERS from group?" }, class: 'btn btn-danger btn-sm'

          %tbody
            - @group.users.each do |user|
              %tr
                %td= user.login
                %td= user.full_name
                %td= user.remark
                %td= link_to 'Remove', remove_user_group_path(@group,user), :method => :delete, :data => { :confirm => "Remove #{user.full_name}?" }, class: 'btn btn-danger btn-sm'
  .col-md-6
    .panel.panel-default
      .panel-heading
        .panel-title Problems
      .panel-body

        =form_tag add_problem_group_path(@group), class: 'form-inline' do
          .form-group
            =label_tag :problem_id, "Problem"
            =select_tag :problem_id, options_from_collection_for_select(Problem.all,'id','full_name'), class: 'select2'
          =submit_tag "Add",class: 'btn btn-primary'


        %table.table.table-hover
          %thead
            %tr
              %th name
              %th Full name
              %th Full score
              %th= link_to 'Remove All', remove_all_problem_group_path(@group), method: :delete, :data => { :confirm => "Remove ALL PROBLEMS from group?" }, class: 'btn btn-danger btn-sm'

          %tbody
            - @group.problems.each do |problem|
              %tr
                %td= problem.name
                %td= problem.full_name
                %td= problem.full_score
                %td= link_to 'Remove', remove_problem_group_path(@group,problem), :method => :delete, :data => { :confirm => "Remove #{problem.full_name}?" }, class: 'btn btn-danger btn-sm'